[1862/autorouter] Fix freight trains not being able to auto route
A minimal repro is here: https://gist.github.com/PistonPercy/dbbad162540451e8941dfae3e57ccbc9

```
Uncaught []: undefined method `[]' for nil
Caused by: Object { … }
klass runtime.js:589
$Exception_new$1 error.rb:12
$$method_missing basic_object.rb:146
method_missing_stub runtime.js:1563
$$adjust_end game.rb:1618
$$hex_crow_distance game.rb:1631
$$freight_revenue game.rb:1671
$$revenue_for game.rb:1676
```

which is originating from this line: https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1862/game.rb#L1618

The issue is the chains from the auto router don't have :hexes, but this code
expects there to be. I'm not sure if :hexes is suppose to be there or the other
side should be tweaked.