[1858] Add a note for a bug that needs to be fixed
Undoing moves can break the game after a company has a token in Lisboa:
{
  "name": "coordinates",
  "message": "undefined method `coordinates' for nil",
  "cause": {
    "name": "coordinates",
    "message": "undefined method `coordinates' for nil",
    "cause": {
      "$$id": 4,
      "elm": {}
    },
    "args": [],
    "backtrace": [
      "http://localhost:9292/assets/deps.js:1523:35:in `method_missing_stub'",
      "http://localhost:9292/assets/g_1858.js:1161:56:in `$$borders_crossed'",
      "http://localhost:9292/assets/g_1858.js:1154:29:in `$$2'",
      "http://localhost:9292/assets/deps.js:1670:14:in `Opal.yield1'",
      "http://localhost:9292/assets/deps.js:13461:28:in `$$collect'",
      "http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'",
      "http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'",
      "http://localhost:9292/assets/deps.js:2154:19:in `alias'",
      "http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'",
      "http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'",
      "http://localhost:9292/assets/g_1858.js:1149:25:in `$Token_adjust_token_price_ability$excl$1'",
      "http://localhost:9292/assets/main.js:30591:21:in `$$place_token'",
      "http://localhost:9292/assets/main.js:30358:16:in `$$process_place_token'"
    ],
    "stack": "  from http://localhost:9292/assets/deps.js:1523:35:in `method_missing_stub'\n  from http://localhost:9292/assets/g_1858.js:1161:56:in `$$borders_crossed'\n  from http://localhost:9292/assets/g_1858.js:1154:29:in `$$2'\n  from http://localhost:9292/assets/deps.js:1670:14:in `Opal.yield1'\n  from http://localhost:9292/assets/deps.js:13461:28:in `$$collect'\n  from http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'\n  from http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'\n  from http://localhost:9292/assets/deps.js:2154:19:in `alias'\n  from http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'\n  from http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'\n  from http://localhost:9292/assets/g_1858.js:1149:25:in `$Token_adjust_token_price_ability$excl$1'\n  from http://localhost:9292/assets/main.js:30591:21:in `$$place_token'\n  from http://localhost:9292/assets/main.js:30358:16:in `$$process_place_token'"
  },
  "args": [],
  "backtrace": [
    "http://localhost:9292/assets/deps.js:1523:35:in `method_missing_stub'",
    "http://localhost:9292/assets/g_1858.js:1161:56:in `$$borders_crossed'",
    "http://localhost:9292/assets/g_1858.js:1154:29:in `$$2'",
    "http://localhost:9292/assets/deps.js:1670:14:in `Opal.yield1'",
    "http://localhost:9292/assets/deps.js:13461:28:in `$$collect'",
    "http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'",
    "http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'",
    "http://localhost:9292/assets/deps.js:2154:19:in `alias'",
    "http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'",
    "http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'",
    "http://localhost:9292/assets/g_1858.js:1149:25:in `$Token_adjust_token_price_ability$excl$1'",
    "http://localhost:9292/assets/main.js:30591:21:in `$$place_token'",
    "http://localhost:9292/assets/main.js:30358:16:in `$$process_place_token'"
  ],
  "stack": "  from http://localhost:9292/assets/deps.js:1523:35:in `method_missing_stub'\n  from http://localhost:9292/assets/g_1858.js:1161:56:in `$$borders_crossed'\n  from http://localhost:9292/assets/g_1858.js:1154:29:in `$$2'\n  from http://localhost:9292/assets/deps.js:1670:14:in `Opal.yield1'\n  from http://localhost:9292/assets/deps.js:13461:28:in `$$collect'\n  from http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'\n  from http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'\n  from http://localhost:9292/assets/deps.js:2154:19:in `alias'\n  from http://localhost:9292/assets/deps.js:1910:17:in `Opal.send2'\n  from http://localhost:9292/assets/deps.js:1898:17:in `Opal.send'\n  from http://localhost:9292/assets/g_1858.js:1149:25:in `$Token_adjust_token_price_ability$excl$1'\n  from http://localhost:9292/assets/main.js:30591:21:in `$$place_token'\n  from http://localhost:9292/assets/main.js:30358:16:in `$$process_place_token'"
}