18LA2: new setup rules for corporations and companies
the new setup rules in 18LA2 are all home tokens (except PER, whose home is
determined on float) are placed at setup and no corporations/companies are
removed, but there is a limit on how many corporations/companies may be
started/drafted (that limit is not implemented here)

exception: 2-player setup now removes *any* 2 random corporations, and still
places two tokens; now all corporations are given a second location, and some of
have changed, so this constant is present in both versions of the game.rb files

* GROUP constants moved to 1st Edition
* 2nd Edition uses new `post_setup` method to place all home corporation tokens;
  1st Edition overrides `post_setup` with a noop
* new method on G1846, `place_second_token_kwargs`, to easily give
  1846/18LA1/18LA2 all different ways of working with a removed corporation's
  second token